name: Example

on:
  push:
    branches:
      - main

jobs:
  message:
    runs-on: ubuntu-latest
steps:
  - name: Create file
    run: |
      echo "This file was created by GitHub Actions" > message.txt

  - name: Show file
    run: cat message.txt